### PR TITLE
Created a Redirect Class

### PR DESCRIPTION
**Pull request by CameronHildebrandt**
All unknown urls now go through a the redirect class by default. If the link is one that we know, we send to the relevant url, if it's not we send to 404 page, and if it's a known link but old, we send to a new "expired link" page.

NewRedirectLoading
subConf
Expired

### CODE REVIEW

**Comment by CameronHildebrandt** [comment]
Idk if y'all can see this, but somehow the picture is in light mode??? I did not implement that, this is always grey, and the photo I have locally is dark mode. Github made a light mode version in the picture???? It high-key slaps tho

Screen Shot 2021-11-11 at 11 14 33 PM

**Review by zacharyselk — CHANGES_REQUESTED** [review]
I cannot check this branch out at all due to the + in `n+uri.png` and `n+uriWhite.png`. Please rename them.
```bash
$ git checkout create-linking-page
error: invalid path 'public/images/event/misc./n+uri.png'
error: invalid path 'public/images/event/misc./n+uriWhite.png'
```

**Comment by CameronHildebrandt** [comment]
renamed files 👍

**Comment by CameronHildebrandt** [comment]
Several updates. Including new linking page:
Screen Shot 2022-03-13 at 11 25 54 PM

**Review by zacharyselk — APPROVED** [review]
Looks good. Theres just the issue of expire being set to "" by default

**Pull request merged**
